####root url, Api test
GET http://localhost:8000/api/v1


### post new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname":"anmol",
    "lname":"bhattarai",
    "email":"a@anmol.com",
    "password":"anmol"
    
   
}

### get user
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email":"assd@gmail.com",
   "password":"aaa"
}


#========transaction api
### post new transaction
POST http://localhost:8000/api/v1/transaction
Content-Type: application/json

{
    "userId":"630752f557b45746291820f0",
   "type":"expense",
   "title":"shopping",
   "amount":300
}
### get the transaction
GET http://localhost:8000/api/v1/transaction
Authorization: 630752f557b45746291820f0



### get the transaction
DELETE http://localhost:8000/api/v1/transaction/6317069bada5369599b0dd1e
Authorization: 630752f557b45746291820f0




