####root url, Api test
GET http://localhost:8000/api/v1


### post new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname":"anmol",
    "lname":"bhattarai",
    "email":"a@anmol.com",
    "password":"anmol"
    
   
}

### get user
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email":"assd@gmail.com",
   "password":"aaa"
}

